export const strings = {
  en:{
    summary:"Kundali Summary", 
    asc:"Ascendant", 
    moon:"Moon Sign", 
    planets:"Planetary Positions", 
    yog:"Yogas", 
    dosh:"Doshas", 
    chat_ph:"Send a message...", 
    send:"Send", 
    upload:"Upload Files", 
    lang:"Language",
    composer:"Type your message...",
    yogas_title:"Yogas",
    doshas_title:"Doshas",
    strength:"Strength",
    weakness:"Weakness",
    moderate:"Moderate",
    no_data:"No data available",
    shadbala:"Shadbala",
    ashtakavarga:"Ashtakavarga",
    dasha_v:"Vimshottari Dasha",
    dasha_y:"Yogini Dasha",
    varga:"Divisional Charts",
    transit:"Transits",
    panchanga:"Panchanga",
    retro:"Retrograde",
    combust:"Combust",
    aspects:"Aspects",
    save_pdf:"Save PDF",
    upload_files:"Upload Files",
    next_periods:"Next Periods",
    active_now:"Active Now",
    coming_soon:"Coming Soon",
    bav:"Bhinnashtakavarga",
    sav:"Sarvashtakavarga",
    points:"Points",
    house:"House",
    navamsa:"Navamsa (D9)",
    dasamsa:"Dasamsa (D10)",
    saptamsa:"Saptamsa (D7)",
    dwadasamsa:"Dwadasamsa (D12)",
    vimsamsa:"Vimsamsa (D20)",
    shashtyamsa:"Shashtyamsa (D60)",
    marriage:"Marriage",
    career:"Career",
    children:"Children",
    parents:"Parents",
    spirituality:"Spirituality",
    karma:"Karma",
    today:"Today",
    tomorrow:"Tomorrow",
    yesterday:"Yesterday",
    tithi:"Tithi",
    vara:"Vara",
    nakshatra:"Nakshatra",
    yoga:"Yoga",
    karana:"Karana"
  },
  hi:{
    summary:"कुंडली सारांश", 
    asc:"लग्न", 
    moon:"चंद्र राशि", 
    planets:"ग्रह स्थिति", 
    yog:"योग", 
    dosh:"दोष", 
    chat_ph:"संदेश लिखें...", 
    send:"भेजें", 
    upload:"फ़ाइल अपलोड", 
    lang:"भाषा",
    composer:"अपना संदेश टाइप करें...",
    yogas_title:"योग",
    doshas_title:"दोष",
    strength:"बल",
    weakness:"कमजोरी",
    moderate:"मध्यम",
    no_data:"कोई डेटा उपलब्ध नहीं",
    shadbala:"षड्बल",
    ashtakavarga:"अष्टकवर्ग",
    dasha_v:"विम्शोत्तरी दशा",
    dasha_y:"योगिनी दशा",
    varga:"वर्ग चार्ट",
    transit:"गोचर",
    panchanga:"पंचांग",
    retro:"वक्री",
    combust:"दहन",
    aspects:"दृष्टि",
    save_pdf:"पीडीएफ सेव करें",
    upload_files:"फ़ाइल अपलोड करें",
    next_periods:"आगामी अवधि",
    active_now:"अभी सक्रिय",
    coming_soon:"जल्द आ रहा",
    bav:"भिन्नाष्टकवर्ग",
    sav:"सर्वाष्टकवर्ग",
    points:"बिन्दु",
    house:"घर",
    navamsa:"नवांश (D9)",
    dasamsa:"दशांश (D10)",
    saptamsa:"सप्तांश (D7)",
    dwadasamsa:"द्वादशांश (D12)",
    vimsamsa:"विंशांश (D20)",
    shashtyamsa:"षष्ट्यांश (D60)",
    marriage:"विवाह",
    career:"करियर",
    children:"संतान",
    parents:"माता-पिता",
    spirituality:"आध्यात्मिकता",
    karma:"कर्म",
    today:"आज",
    tomorrow:"कल",
    yesterday:"बीता कल",
    tithi:"तिथि",
    vara:"वार",
    nakshatra:"नक्षत्र",
    yoga:"योग",
    karana:"करण"
  },
  ne:{
    summary:"कुण्डली सारांश", 
    asc:"लग्न", 
    moon:"चन्द्र राशी", 
    planets:"ग्रह स्थिति", 
    yog:"योग", 
    dosh:"दोष", 
    chat_ph:"सन्देश पठाउनुहोस्...", 
    send:"पठाउनुहोस्", 
    upload:"फाइल अपलोड", 
    lang:"भाषा",
    composer:"आफ्नो सन्देश टाइप गर्नुहोस्...",
    yogas_title:"योग",
    doshas_title:"दोष",
    strength:"बल",
    weakness:"कमजोरी",
    moderate:"मध्यम",
    no_data:"कुनै डेटा उपलब्ध छैन",
    shadbala:"षड्बल",
    ashtakavarga:"अष्टकवर्ग",
    dasha_v:"विम्शोत्तरी दशा",
    dasha_y:"योगिनी दशा",
    varga:"वर्ग चार्ट",
    transit:"गोचर",
    panchanga:"पंचांग",
    retro:"वक्री",
    combust:"दहन",
    aspects:"दृष्टि",
    save_pdf:"पीडीएफ सेव गर्नुहोस्",
    upload_files:"फाइल अपलोड गर्नुहोस्",
    next_periods:"आगामी अवधि",
    active_now:"अहिले सक्रिय",
    coming_soon:"छिट्टै आउँदै",
    bav:"भिन्नाष्टकवर्ग",
    sav:"सर्वाष्टकवर्ग",
    points:"बिन्दु",
    house:"घर",
    navamsa:"नवांश (D9)",
    dasamsa:"दशांश (D10)",
    saptamsa:"सप्तांश (D7)",
    dwadasamsa:"द्वादशांश (D12)",
    vimsamsa:"विंशांश (D20)",
    shashtyamsa:"षष्ट्यांश (D60)",
    marriage:"विवाह",
    career:"करियर",
    children:"सन्तान",
    parents:"आमा-बुबा",
    spirituality:"आध्यात्मिकता",
    karma:"कर्म",
    today:"आज",
    tomorrow:"भोलि",
    yesterday:"हिजो",
    tithi:"तिथि",
    vara:"वार",
    nakshatra:"नक्षत्र",
    yoga:"योग",
    karana:"करण"
  },
};

export const getString = (key: keyof typeof strings["en"], lang: "en" | "hi" | "ne") => {
  return strings[lang][key] || strings["en"][key];
};