export const strings = {
  en: {
    summary: "Kundali Summary",
    asc: "Ascendant",
    moon: "Moon Sign",
    planets: "Planetary Positions",
    yog: "Yogas",
    dosh: "Doshas",
    pdf: "PDF Download",
    upload: "Upload Files",
    composer: "Ask your question...",
    sun: "Sun",
    moon_planet: "Moon",
    mars: "Mars",
    mercury: "Mercury",
    jupiter: "Jupiter",
    venus: "Venus",
    saturn: "Saturn",
    rahu: "Rahu",
    ketu: "Ketu",
    house: "House",
    degree: "Degree",
    shadbala: "Shadbala",
    total: "Total",
    sthana: "Sthana",
    dig: "Dig",
    kala: "Kala",
    chestha: "Chestha",
    naisargika: "Naisargika",
    drik: "Drik",
    vimshottari: "Vimshottari Dasha",
    yogini: "Yogini Dasha",
    dasha: "Dasha",
    lord: "Lord",
    start: "Start",
    end: "End",
    level: "Level",
    maha: "Maha",
    antar: "Antar",
    pratyantar: "Pratyantar",
    sukshma: "Sukshma",
    prana: "Prana",
    yogini_level: "Yogini",
    no_data: "No data available",
    loading: "Loading...",
    error: "Error loading data",
    retry: "Retry",
    close: "Close",
    open: "Open",
    send_to_chat: "Send to Chat",
    choose_file: "Choose File",
    drag_drop: "Drag & drop files here",
    max_size: "Max size",
    file_type: "File type",
    pdf_file: "PDF Document",
    image_file: "Image",
    extracted_text: "Extracted text",
    no_text: "No text content extracted",
    image_uploaded: "Image uploaded — OCR not enabled",
    upload_success: "File uploaded successfully",
    upload_error: "Upload failed",
    extract_error: "Extraction failed",
    file_too_large: "File size exceeds limit",
    unsupported_type: "Unsupported file type",
    generating_pdf: "Generating PDF...",
    pdf_generated: "PDF generated successfully",
    pdf_error: "Failed to generate PDF",
    chart_not_ready: "Chart not ready. Please wait for the chart to load.",
    report_date: "Report Date",
    uploaded_files: "Uploaded Files Summary",
    planetary_positions: "Planetary Positions",
    shadbala_summary: "Shadbala Summary",
    dasha_listings: "Dasha Listings",
    download_kundali: "Download Kundali PDF",
    export_report: "Export Report",
    complete_pdf_report: "Download a complete PDF report with chart, planetary positions, and analysis.",
    if_files_uploaded: "If files are uploaded, a summary of their content will also be included.",
    aries: "Aries",
    taurus: "Taurus",
    gemini: "Gemini",
    cancer: "Cancer",
    leo: "Leo",
    virgo: "Virgo",
    libra: "Libra",
    scorpio: "Scorpio",
    sagittarius: "Sagittarius",
    capricorn: "Capricorn",
    aquarius: "Aquarius",
    pisces: "Pisces"
  },
  hi: {
    summary: "कुंडली सारांश",
    asc: "लग्न",
    moon: "चंद्र राशि",
    planets: "ग्रह स्थिति",
    yog: "योग",
    dosh: "दोष",
    pdf: "पीडीएफ डाउनलोड",
    upload: "फ़ाइल अपलोड करें",
    composer: "अपना प्रश्न लिखें...",
    sun: "सूर्य",
    moon_planet: "चंद्र",
    mars: "मंगल",
    mercury: "बुध",
    jupiter: "गुरु",
    venus: "शुक्र",
    saturn: "शनि",
    rahu: "राहु",
    ketu: "केतु",
    house: "घर",
    degree: "डिग्री",
    shadbala: "षड्बल",
    total: "कुल",
    sthana: "स्थान",
    dig: "दिग",
    kala: "काल",
    chestha: "चेष्टा",
    naisargika: "नैसर्गिक",
    drik: "दृक",
    vimshottari: "विम्शोत्तरी दशा",
    yogini: "योगिनी दशा",
    dasha: "दशा",
    lord: "स्वामी",
    start: "शुरुआत",
    end: "अंत",
    level: "स्तर",
    maha: "महा",
    antar: "अंतर",
    pratyantar: "प्रत्यंतर",
    sukshma: "सूक्ष्म",
    prana: "प्राण",
    yogini_level: "योगिनी",
    no_data: "कोई डेटा उपलब्ध नहीं",
    loading: "लोड हो रहा है...",
    error: "डेटा लोड करने में त्रुटि",
    retry: "पुनः प्रयास",
    close: "बंद करें",
    open: "खोलें",
    send_to_chat: "चैट में भेजें",
    choose_file: "फ़ाइल चुनें",
    drag_drop: "फ़ाइलें यहाँ खींचें और छोड़ें",
    max_size: "अधिकतम आकार",
    file_type: "फ़ाइल प्रकार",
    pdf_file: "पीडीएफ दस्तावेज़",
    image_file: "छवि",
    extracted_text: "निकाला गया पाठ",
    no_text: "कोई पाठ सामग्री नहीं निकाली गई",
    image_uploaded: "छवि अपलोड की गई — OCR सक्षम नहीं",
    upload_success: "फ़ाइल सफलतापूर्वक अपलोड की गई",
    upload_error: "अपलोड विफल",
    extract_error: "निष्कर्षण विफल",
    file_too_large: "फ़ाइल का आकार सीमा से अधिक है",
    unsupported_type: "असमर्थित फ़ाइल प्रकार",
    generating_pdf: "पीडीएफ जेनरेट हो रहा है...",
    pdf_generated: "पीडीएफ सफलतापूर्वक जेनरेट हुआ",
    pdf_error: "पीडीएफ जेनरेट करने में विफल",
    chart_not_ready: "चार्ट तैयार नहीं है। कृपया चार्ट लोड होने का इंतजार करें।",
    report_date: "रिपोर्ट की तारीख",
    uploaded_files: "अपलोड की गई फ़ाइलों का सारांश",
    planetary_positions: "ग्रह स्थिति",
    shadbala_summary: "षड्बल सारांश",
    dasha_listings: "दशा सूची",
    download_kundali: "कुंडली पीडीएफ डाउनलोड करें",
    export_report: "रिपोर्ट निर्यात करें",
    complete_pdf_report: "चार्ट, ग्रह स्थिति और विश्लेषण के साथ एक पूर्ण पीडीएफ रिपोर्ट डाउनलोड करें।",
    if_files_uploaded: "यदि फ़ाइलें अपलोड की गई हैं, तो उनकी सामग्री का सारांश भी शामिल होगा।",
    aries: "मेष",
    taurus: "वृष",
    gemini: "मिथुन",
    cancer: "कर्क",
    leo: "सिंह",
    virgo: "कन्या",
    libra: "तुला",
    scorpio: "वृश्चिक",
    sagittarius: "धनु",
    capricorn: "मकर",
    aquarius: "कुम्भ",
    pisces: "मीन"
  },
  ne: {
    summary: "कुण्डली सारांश",
    asc: "लग्न",
    moon: "चन्द्र राशी",
    planets: "ग्रह स्थिति",
    yog: "योग",
    dosh: "दोष",
    pdf: "पीडीएफ डाउनलोड",
    upload: "फाइल अपलोड गर्नुहोस्",
    composer: "आफ्नो प्रश्न लेख्नुहोस्...",
    sun: "सूर्य",
    moon_planet: "चन्द्र",
    mars: "मंगल",
    mercury: "बुध",
    jupiter: "गुरु",
    venus: "शुक्र",
    saturn: "शनि",
    rahu: "राहु",
    ketu: "केतु",
    house: "घर",
    degree: "डिग्री",
    shadbala: "षड्बल",
    total: "कुल",
    sthana: "स्थान",
    dig: "दिग",
    kala: "काल",
    chestha: "चेष्टा",
    naisargika: "नैसर्गिक",
    drik: "दृक",
    vimshottari: "विम्शोत्तरी दशा",
    yogini: "योगिनी दशा",
    dasha: "दशा",
    lord: "स्वामी",
    start: "शुरु",
    end: "अन्त",
    level: "तह",
    maha: "महा",
    antar: "अन्तर",
    pratyantar: "प्रत्यन्तर",
    sukshma: "सूक्ष्म",
    prana: "प्राण",
    yogini_level: "योगिनी",
    no_data: "कुनै डेटा उपलब्ध छैन",
    loading: "लोड हुँदैछ...",
    error: "डेटा लोड गर्नमा त्रुटि",
    retry: "पुनः प्रयास",
    close: "बन्द गर्नुहोस्",
    open: "खोल्नुहोस्",
    send_to_chat: "च्याटमा पठाउनुहोस्",
    choose_file: "फाइल छान्नुहोस्",
    drag_drop: "फाइलहरू यहाँ तान्नुहोस् र छोड्नुहोस्",
    max_size: "अधिकतम आकार",
    file_type: "फाइल प्रकार",
    pdf_file: "पीडीएफ दस्तावेज",
    image_file: "छवि",
    extracted_text: "निकालिएको पाठ",
    no_text: "कुनै पाठ सामग्री निकालिएको छैन",
    image_uploaded: "छवि अपलोड गरिएको — OCR सक्षम छैन",
    upload_success: "फाइल सफलतापूर्वक अपलोड गरिएको",
    upload_error: "अपलोड असफल",
    extract_error: "निष्कर्षण असफल",
    file_too_large: "फाइलको आकार सीमा भन्दा बढी छ",
    unsupported_type: "असमर्थित फाइल प्रकार",
    generating_pdf: "पीडीएफ जेनरेट हुँदैछ...",
    pdf_generated: "पीडीएफ सफलतापूर्वक जेनरेट भयो",
    pdf_error: "पीडीएफ जेनरेट गर्न असफल",
    chart_not_ready: "चार्ट तयार छैन। कृपया चार्ट लोड हुनको लागि प्रतीक्षा गर्नुहोस्।",
    report_date: "रिपोर्ट मिति",
    uploaded_files: "अपलोड गरिएका फाइलहरूको सारांश",
    planetary_positions: "ग्रह स्थिति",
    shadbala_summary: "षड्बल सारांश",
    dasha_listings: "दशा सूची",
    download_kundali: "कुण्डली पीडीएफ डाउनलोड गर्नुहोस्",
    export_report: "रिपोर्ट निर्यात गर्नुहोस्",
    complete_pdf_report: "चार्ट, ग्रह स्थिति र विश्लेषणको साथ एक पूर्ण पीडीएफ रिपोर्ट डाउनलोड गर्नुहोस्।",
    if_files_uploaded: "यदि फाइलहरू अपलोड गरिएका छन्, तिनीहरूको सामग्रीको सारांश पनि समावेश हुनेछ।",
    aries: "मेष",
    taurus: "वृष",
    gemini: "मिथुन",
    cancer: "कर्क",
    leo: "सिंह",
    virgo: "कन्या",
    libra: "तुला",
    scorpio: "वृश्चिक",
    sagittarius: "धनु",
    capricorn: "मकर",
    aquarius: "कुम्भ",
    pisces: "मीन"
  }
};

export function getString(key: keyof typeof strings.en, lang: "en" | "hi" | "ne" = "en"): string {
  return strings[lang][key] || strings.en[key] || key;
}

export function getPlanetName(planet: string, lang: "en" | "hi" | "ne" = "en"): string {
  const planetMap: Record<string, keyof typeof strings.en> = {
    "Sun": "sun",
    "Moon": "moon_planet",
    "Mars": "mars",
    "Mercury": "mercury",
    "Jupiter": "jupiter",
    "Venus": "venus",
    "Saturn": "saturn",
    "Rahu": "rahu",
    "Ketu": "ketu"
  };
  
  const key = planetMap[planet];
  return key ? getString(key, lang) : planet;
}

export function getSignName(signId: number, lang: "en" | "hi" | "ne" = "en"): string {
  const signMap: Record<number, keyof typeof strings.en> = {
    1: "aries",
    2: "taurus", 
    3: "gemini",
    4: "cancer",
    5: "leo",
    6: "virgo",
    7: "libra",
    8: "scorpio",
    9: "sagittarius",
    10: "capricorn",
    11: "aquarius",
    12: "pisces"
  };
  
  const key = signMap[signId];
  return key ? getString(key, lang) : `Sign ${signId}`;
}
